# Generated by Django 5.2.8 on 2025-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uz',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
