# Generated by Django 5.2.8 on 2025-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_city_name_en_city_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
